import { Product, Category, Division } from './types';
import { FishIcon, MeatIcon, FruitIcon, VegetableIcon, SpiceIcon, GroceryIcon, AllIcon } from './components/icons';

export const DIVISIONS: Division[] = [
  { name: 'Dhaka', bn_name: 'ঢাকা', price_multiplier: 1.05 },
  { name: 'Chittagong', bn_name: 'চট্টগ্রাম', price_multiplier: 1.02 },
  { name: 'Rajshahi', bn_name: 'রাজশাহী', price_multiplier: 0.98 },
  { name: 'Khulna', bn_name: 'খুলনা', price_multiplier: 0.97 },
  { name: 'Barisal', bn_name: 'বরিশাল', price_multiplier: 0.95 },
  { name: 'Sylhet', bn_name: 'সিলেট', price_multiplier: 1.00 },
  { name: 'Rangpur', bn_name: 'রংপুর', price_multiplier: 0.93 },
  { name: 'Mymensingh', bn_name: 'ময়মনসিংহ', price_multiplier: 0.96 },
];

export const CATEGORIES: Category[] = [
  { id: 'All', name_en: 'All', name_bn: 'সব', icon: AllIcon },
  { id: 'Fish', name_en: 'Fish', name_bn: 'মাছ', icon: FishIcon },
  { id: 'Meat', name_en: 'Meat', name_bn: 'মাংস', icon: MeatIcon },
  { id: 'Vegetables', name_en: 'Vegetables', name_bn: 'সবজি', icon: VegetableIcon },
  { id: 'Fruits', name_en: 'Fruits', name_bn: 'ফল', icon: FruitIcon },
  { id: 'Spices', name_en: 'Spices', name_bn: 'মসলা', icon: SpiceIcon },
  { id: 'Groceries', name_en: 'Groceries', name_bn: 'মুদি', icon: GroceryIcon },
];

export const PRODUCTS: Omit<Product, 'price' | 'image_url'>[] = [
  // Fish
  { id: 1, name_en: 'Hilsha Fish', name_bn: 'ইলিশ মাছ', category: 'Fish', unit: 'কেজি', base_price: 1200 },
  { id: 2, name_en: 'Rohu Fish', name_bn: 'রুই মাছ', category: 'Fish', unit: 'কেজি', base_price: 350 },
  { id: 3, name_en: 'Catla Fish', name_bn: 'কাতলা মাছ', category: 'Fish', unit: 'কেজি', base_price: 380 },
  { id: 4, name_en: 'Pangas Fish', name_bn: 'পাঙ্গাস মাছ', category: 'Fish', unit: 'কেজি', base_price: 180 },
  { id: 5, name_en: 'Tilapia Fish', name_bn: 'তেলাপিয়া মাছ', category: 'Fish', unit: 'কেজি', base_price: 200 },
  { id: 6, name_en: 'Shrimp', name_bn: 'চিংড়ি', category: 'Fish', unit: 'কেজি', base_price: 800 },
  { id: 7, name_en: 'Pabda Fish', name_bn: 'পাবদা মাছ', category: 'Fish', unit: 'কেজি', base_price: 600 },
  { id: 88, name_en: 'Koi Fish', name_bn: 'কৈ মাছ', category: 'Fish', unit: 'কেজি', base_price: 400 },
  { id: 89, name_en: 'Magur Fish', name_bn: 'মাগুর মাছ', category: 'Fish', unit: 'কেজি', base_price: 550 },
  { id: 90, name_en: 'Shing Fish', name_bn: 'শিং মাছ', category: 'Fish', unit: 'কেজি', base_price: 500 },
  { id: 91, name_en: 'Boal Fish', name_bn: 'বোয়াল মাছ', category: 'Fish', unit: 'কেজি', base_price: 650 },
  { id: 92, name_en: 'Loitta Fish', name_bn: 'লইট্টা মাছ', category: 'Fish', unit: 'কেজি', base_price: 250 },
  { id: 93, name_en: 'Rupchanda Fish', name_bn: 'রূপচাঁদা মাছ', category: 'Fish', unit: 'কেজি', base_price: 900 },
  { id: 94, name_en: 'Koral Fish', name_bn: 'কোরাল মাছ', category: 'Fish', unit: 'কেজি', base_price: 700 },
  { id: 95, name_en: 'Bata Fish', name_bn: 'বাটা মাছ', category: 'Fish', unit: 'কেজি', base_price: 300 },
  { id: 96, name_en: 'Tengra Fish', name_bn: 'টেংরা মাছ', category: 'Fish', unit: 'কেজি', base_price: 450 },
  { id: 97, name_en: 'Ayer Fish', name_bn: 'আইড় মাছ', category: 'Fish', unit: 'কেজি', base_price: 750 },
  { id: 98, name_en: 'Bhetki Fish', name_bn: 'ভেটকি মাছ', category: 'Fish', unit: 'কেজি', base_price: 800 },
  { id: 99, name_en: 'Shorputi', name_bn: 'সরপুঁটি', category: 'Fish', unit: 'কেজি', base_price: 280 },


  // Meat
  { id: 11, name_en: 'Beef', name_bn: 'গরুর মাংস', category: 'Meat', unit: 'কেজি', base_price: 750 },
  { id: 12, name_en: 'Mutton', name_bn: 'খাসির মাংস', category: 'Meat', unit: 'কেজি', base_price: 1100 },
  { id: 13, name_en: 'Broiler Chicken', name_bn: 'ব্রয়লার মুরগি', category: 'Meat', unit: 'কেজি', base_price: 220 },
  { id: 14, name_en: 'Sonali Chicken', name_bn: 'সোনালী মুরগি', category: 'Meat', unit: 'কেজি', base_price: 340 },
  { id: 15, name_en: 'Duck Meat', name_bn: 'হাঁসের মাংস', category: 'Meat', unit: 'কেজি', base_price: 550 },
  { id: 100, name_en: 'Quail Meat', name_bn: 'কোয়েলের মাংস', category: 'Meat', unit: 'পিস', base_price: 60 },
  { id: 101, name_en: 'Pigeon Meat', name_bn: 'কবুতরের মাংস', category: 'Meat', unit: 'পিস', base_price: 200 },
  { id: 102, name_en: 'Beef Liver', name_bn: 'গরুর কলিজা', category: 'Meat', unit: 'কেজি', base_price: 800 },
  { id: 103, name_en: 'Mutton Liver', name_bn: 'খাসির কলিজা', category: 'Meat', unit: 'কেজি', base_price: 1150 },
  { id: 104, name_en: 'Chicken Liver', name_bn: 'মুরগির কলিজা', category: 'Meat', unit: 'কেজি', base_price: 300 },
  { id: 105, name_en: 'Beef Brain', name_bn: 'গরুর মগজ', category: 'Meat', unit: 'পিস', base_price: 150 },
  { id: 106, name_en: 'Mutton Leg', name_bn: 'খাসির রান', category: 'Meat', unit: 'কেজি', base_price: 1200 },

  // Vegetables
  { id: 21, name_en: 'Potato', name_bn: 'আলু', category: 'Vegetables', unit: 'কেজি', base_price: 50 },
  { id: 22, name_en: 'Onion', name_bn: 'পেঁয়াজ', category: 'Vegetables', unit: 'কেজি', base_price: 90 },
  { id: 23, name_en: 'Tomato', name_bn: 'টমেটো', category: 'Vegetables', unit: 'কেজি', base_price: 60 },
  { id: 24, name_en: 'Brinjal', name_bn: 'বেগুন', category: 'Vegetables', unit: 'কেজি', base_price: 70 },
  { id: 25, name_en: 'Cucumber', name_bn: 'শসা', category: 'Vegetables', unit: 'কেজি', base_price: 60 },
  { id: 26, name_en: 'Lady\'s Finger', name_bn: 'ঢেঁড়স', category: 'Vegetables', unit: 'কেজি', base_price: 50 },
  { id: 27, name_en: 'Cauliflower', name_bn: 'ফুলকপি', category: 'Vegetables', unit: 'পিস', base_price: 40 },
  { id: 28, name_en: 'Cabbage', name_bn: 'বাঁধাকপি', category: 'Vegetables', unit: 'পিস', base_price: 35 },
  { id: 29, name_en: 'Green Chili', name_bn: 'কাঁচা মরিচ', category: 'Vegetables', unit: 'কেজি', base_price: 120 },
  { id: 107, name_en: 'Pointed Gourd', name_bn: 'পটল', category: 'Vegetables', unit: 'কেজি', base_price: 40 },
  { id: 108, name_en: 'Ridge Gourd', name_bn: 'চিচিঙ্গা', category: 'Vegetables', unit: 'কেজি', base_price: 50 },
  { id: 109, name_en: 'Snake Gourd', name_bn: 'ঝিঙ্গা', category: 'Vegetables', unit: 'কেজি', base_price: 60 },
  { id: 110, name_en: 'Bitter Gourd', name_bn: 'করলা', category: 'Vegetables', unit: 'কেজি', base_price: 70 },
  { id: 111, name_en: 'Bottle Gourd', name_bn: 'লাউ', category: 'Vegetables', unit: 'পিস', base_price: 50 },
  { id: 112, name_en: 'Pumpkin', name_bn: 'মিষ্টি কুমড়া', category: 'Vegetables', unit: 'কেজি', base_price: 30 },
  { id: 113, name_en: 'Radish', name_bn: 'মূলা', category: 'Vegetables', unit: 'কেজি', base_price: 40 },
  { id: 114, name_en: 'Carrot', name_bn: 'গাজর', category: 'Vegetables', unit: 'কেজি', base_price: 80 },
  { id: 115, name_en: 'Bean', name_bn: 'শিম', category: 'Vegetables', unit: 'কেজি', base_price: 60 },
  { id: 116, name_en: 'Yardlong Bean', name_bn: 'বরবটি', category: 'Vegetables', unit: 'কেজি', base_price: 70 },
  { id: 117, name_en: 'Papaya (Raw)', name_bn: 'কাঁচা পেঁপে', category: 'Vegetables', unit: 'কেজি', base_price: 40 },
  { id: 118, name_en: 'Taro Root', name_bn: 'কচু', category: 'Vegetables', unit: 'কেজি', base_price: 60 },
  { id: 119, name_en: 'Taro Stem', name_bn: 'কচুর লতি', category: 'Vegetables', unit: 'আঁটি', base_price: 30 },
  { id: 120, name_en: 'Spinach', name_bn: 'পালং শাক', category: 'Vegetables', unit: 'আঁটি', base_price: 20 },
  { id: 121, name_en: 'Red Amaranth', name_bn: 'লাল শাক', category: 'Vegetables', unit: 'আঁটি', base_price: 15 },
  { id: 122, name_en: 'Drumstick', name_bn: 'সজনে', category: 'Vegetables', unit: 'কেজি', base_price: 100 },
  { id: 123, name_en: 'Broccoli', name_bn: 'ব্রোকলি', category: 'Vegetables', unit: 'পিস', base_price: 70 },
  { id: 124, name_en: 'Capsicum', name_bn: 'ক্যাপসিকাম', category: 'Vegetables', unit: 'কেজি', base_price: 200 },
  { id: 125, name_en: 'Lemon', name_bn: 'লেবু', category: 'Vegetables', unit: 'হালি', base_price: 30 },

  // Fruits
  { id: 41, name_en: 'Mango', name_bn: 'আম', category: 'Fruits', unit: 'কেজি', base_price: 100 },
  { id: 42, name_en: 'Banana', name_bn: 'কলা', category: 'Fruits', unit: 'ডজন', base_price: 120 },
  { id: 43, name_en: 'Apple', name_bn: 'আপেল', category: 'Fruits', unit: 'কেজি', base_price: 250 },
  { id: 44, name_en: 'Guava', name_bn: 'পেয়ারা', category: 'Fruits', unit: 'কেজি', base_price: 80 },
  { id: 45, name_en: 'Jackfruit', name_bn: 'কাঁঠাল', category: 'Fruits', unit: 'পিস', base_price: 300 },
  { id: 46, name_en: 'Pineapple', name_bn: 'আনারস', category: 'Fruits', unit: 'পিস', base_price: 60 },
  { id: 47, name_en: 'Watermelon', name_bn: 'তরমুজ', category: 'Fruits', unit: 'কেজি', base_price: 50 },
  { id: 126, name_en: 'Litchi', name_bn: 'লিচু', category: 'Fruits', unit: '১০০ পিস', base_price: 350 },
  { id: 127, name_en: 'Blackberry', name_bn: 'জাম', category: 'Fruits', unit: 'কেজি', base_price: 120 },
  { id: 128, name_en: 'Pomegranate', name_bn: 'ডালিম', category: 'Fruits', unit: 'কেজি', base_price: 300 },
  { id: 129, name_en: 'Orange', name_bn: 'কমলা', category: 'Fruits', unit: 'কেজি', base_price: 180 },
  { id: 130, name_en: 'Malta', name_bn: 'মাল্টা', category: 'Fruits', unit: 'কেজি', base_price: 160 },
  { id: 131, name_en: 'Grapes', name_bn: 'আঙ্গুর', category: 'Fruits', unit: 'কেজি', base_price: 350 },
  { id: 132, name_en: 'Papaya (Ripe)', name_bn: 'পাকা পেঁপে', category: 'Fruits', unit: 'কেজি', base_price: 90 },
  { id: 133, name_en: 'Jujube', name_bn: 'বরই', category: 'Fruits', unit: 'কেজি', base_price: 80 },
  { id: 134, name_en: 'Wood Apple', name_bn: 'বেল', category: 'Fruits', unit: 'পিস', base_price: 40 },
  { id: 135, name_en: 'Star Fruit', name_bn: 'কামরাঙা', category: 'Fruits', unit: 'কেজি', base_price: 70 },
  { id: 136, name_en: 'Dates', name_bn: 'খেজুর', category: 'Fruits', unit: 'কেজি', base_price: 600 },
  { id: 137, name_en: 'Coconut', name_bn: 'নারিকেল', category: 'Fruits', unit: 'পিস', base_price: 70 },

  // Spices
  { id: 61, name_en: 'Garlic', name_bn: 'রসুন', category: 'Spices', unit: 'কেজি', base_price: 220 },
  { id: 62, name_en: 'Ginger', name_bn: 'আদা', category: 'Spices', unit: 'কেজি', base_price: 250 },
  { id: 63, name_en: 'Turmeric Powder', name_bn: 'হলুদ গুঁড়া', category: 'Spices', unit: 'কেজি', base_price: 300 },
  { id: 64, name_en: 'Chili Powder', name_bn: 'মরিচ গুঁড়া', category: 'Spices', unit: 'কেজি', base_price: 450 },
  { id: 65, name_en: 'Coriander Powder', name_bn: 'ধনিয়া গুঁড়া', category: 'Spices', unit: 'কেজি', base_price: 280 },
  { id: 66, name_en: 'Cinnamon', name_bn: 'দারুচিনি', category: 'Spices', unit: '১০০ গ্রাম', base_price: 50 },
  { id: 138, name_en: 'Cumin', name_bn: 'জিরা', category: 'Spices', unit: '১০০ গ্রাম', base_price: 80 },
  { id: 139, name_en: 'Bay Leaf', name_bn: 'তেজপাতা', category: 'Spices', unit: '৫০ গ্রাম', base_price: 30 },
  { id: 140, name_en: 'Cardamom', name_bn: 'এলাচ', category: 'Spices', unit: '১০ গ্রাম', base_price: 100 },
  { id: 141, name_en: 'Clove', name_bn: 'লবঙ্গ', category: 'Spices', unit: '১০ গ্রাম', base_price: 50 },
  { id: 142, name_en: 'Black Pepper', name_bn: 'গোল মরিচ', category: 'Spices', unit: '৫০ গ্রাম', base_price: 120 },
  { id: 143, name_en: 'Mustard Seed', name_bn: 'সরিষা', category: 'Spices', unit: '১০০ গ্রাম', base_price: 40 },
  { id: 144, name_en: 'Nutmeg', name_bn: 'জায়ফল', category: 'Spices', unit: 'পিস', base_price: 20 },
  { id: 145, name_en: 'Mace', name_bn: 'জয়ত্রী', category: 'Spices', unit: '১০ গ্রাম', base_price: 60 },

  // Groceries
  { id: 81, name_en: 'Rice (Miniket)', name_bn: 'চাল (মিনিকেট)', category: 'Groceries', unit: 'কেজি', base_price: 70 },
  { id: 82, name_en: 'Lentil (Masoor)', name_bn: 'মসুর ডাল', category: 'Groceries', unit: 'কেজি', base_price: 140 },
  { id: 83, name_en: 'Soybean Oil', name_bn: 'সয়াবিন তেল', category: 'Groceries', unit: 'লিটার', base_price: 160 },
  { id: 84, name_en: 'Sugar', name_bn: 'চিনি', category: 'Groceries', unit: 'কেজি', base_price: 140 },
  { id: 85, name_en: 'Salt', name_bn: 'লবণ', category: 'Groceries', unit: 'কেজি', base_price: 42 },
  { id: 86, name_en: 'Flour (Atta)', name_bn: 'আটা', category: 'Groceries', unit: 'কেজি', base_price: 60 },
  { id: 87, name_en: 'Egg', name_bn: 'ডিম', category: 'Groceries', unit: 'ডজন', base_price: 150 },
  { id: 146, name_en: 'Mustard Oil', name_bn: 'সরিষার তেল', category: 'Groceries', unit: 'লিটার', base_price: 280 },
  { id: 147, name_en: 'Ghee', name_bn: 'ঘি', category: 'Groceries', unit: 'কেজি', base_price: 1200 },
  { id: 148, name_en: 'Semolina', name_bn: 'সুজি', category: 'Groceries', unit: '৫০০ গ্রাম', base_price: 50 },
  { id: 149, name_en: 'Flattened Rice', name_bn: 'চিড়া', category: 'Groceries', unit: 'কেজি', base_price: 80 },
  { id: 150, name_en: 'Puffed Rice', name_bn: 'মুড়ি', category: 'Groceries', unit: 'কেজি', base_price: 90 },
  { id: 151, name_en: 'Molasses', name_bn: 'গুড়', category: 'Groceries', unit: 'কেজি', base_price: 120 },
  { id: 152, name_en: 'Chickpea', name_bn: 'ছোলা', category: 'Groceries', unit: 'কেজি', base_price: 110 },
  { id: 153, name_en: 'Moong Dal', name_bn: 'মুগ ডাল', category: 'Groceries', unit: 'কেজি', base_price: 160 },
  { id: 154, name_en: 'Gram Flour', name_bn: 'বেসন', category: 'Groceries', unit: 'কেজি', base_price: 100 },
  { id: 155, name_en: 'Milk Powder', name_bn: 'গুঁড়া দুধ', category: 'Groceries', unit: 'কেজি', base_price: 850 },
  { id: 156, name_en: 'Tea', name_bn: 'চা পাতা', category: 'Groceries', unit: '৪০০ গ্রাম', base_price: 250 },
  { id: 157, name_en: 'Noodles', name_bn: 'নুডুলস', category: 'Groceries', unit: 'প্যাক', base_price: 30 },
  { id: 158, name_en: 'Bread', name_bn: 'পাউরুটি', category: 'Groceries', unit: 'পিস', base_price: 60 },
  { id: 159, name_en: 'Biscuit', name_bn: 'বিস্কুট', category: 'Groceries', unit: 'প্যাকেট', base_price: 40 },
  { id: 160, name_en: 'Detergent', name_bn: 'ডিটারজেন্ট', category: 'Groceries', unit: 'কেজি', base_price: 150 },
];